{
  "schema_version": "1.4.0",
  "id": "GHSA-m87m-mmvp-v9qm",
  "modified": "2024-06-05T15:30:39Z",
  "published": "2024-06-05T15:30:39Z",
  "aliases": [
    "CVE-2024-5629"
  ],
  "details": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:N/A:L"
    }
  ],
  "affected": [

  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2024-5629"
    },
    {
      "type": "WEB",
      "url": "https://jira.mongodb.org/browse/PYTHON-4305"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-06-05T15:15:12Z"
  }
}